[WIP] Tests for autonomy package
valory-xyz/open-autonomy pull request #1046
Opened 2022-07-02 04:24 UTC by angrybayblade

## Proposed changes

This PR adds tests for autonomy package

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [ ] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [ ] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have locally run services that could be impacted and they do not present failures derived from my changes

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-07-02 04:25 UTC, angrybayblade commented on autonomy/cli/hash.py
> +def hash_file(path: str, no_wrap: bool) -> None:  # pragma: nocover
TODO: remove no cover marker and add tests

2022-07-02 09:05 UTC, DavidMinarsch requested changes
Good progress but I would like to see less branches ignored. Testing these negative cases is also helpful!

2022-07-02 09:05 UTC, DavidMinarsch commented on autonomy/analyse/abci/logs.py
> +                if agent_id not in periods.keys():  # pragma: nocover
It would be good to have tests for these cases too?

2022-07-02 09:05 UTC, DavidMinarsch commented on autonomy/analyse/abci/handlers.py
> +    except ModuleNotFoundError as exc:  # pragma: nocover
Ideally, we have tests for these cases too.

2022-07-02 09:05 UTC, DavidMinarsch commented on autonomy/cli/deploy.py
> +        raise click.ClickException(  # pragma: nocover
See above, we should also test our error handling!

2022-07-02 09:05 UTC, DavidMinarsch commented on autonomy/cli/fetch.py
> +        else:  # pragma: nocover
Let's test these ignored branches too

2022-07-02 09:05 UTC, DavidMinarsch commented on autonomy/cli/hash.py
> +                    continue  # pragma: nocover
Please include in tests

2022-07-02 09:05 UTC, DavidMinarsch commented on autonomy/cli/hash.py
> +    if check:  # pragma: nocover
Test too

2022-07-05 16:48 UTC, angrybayblade commented on autonomy/analyse/abci/app_spec.py
> +class DFA:  # pragma: nocover
I think Jose would be more suitable to write tests for this class.

2022-07-05 16:48 UTC, angrybayblade commented on autonomy/analyse/abci/logs.py
> +    for error in errors:  # pragma: nocover
Same goes with this function, I think David V would be more suitable to write tests for this method.

2022-07-05 16:48 UTC, angrybayblade commented on autonomy/cli/fetch.py
>              do_fetch(ctx, public_id, alias)
This is already being tested on open-aea.

2022-07-05 16:48 UTC, angrybayblade commented on autonomy/cli/publish.py
>              publish_agent_package(click_context, registry, push_missing)
Same as above

2022-07-05 16:48 UTC, angrybayblade commented on autonomy/cli/replay.py
>          docker_compose_config = yaml.safe_load(fp)
`load_docker_config` is patched during tests and this logic is only a wrapper around `yaml.safe_load` so I don't think we need to test this.

2022-07-05 19:13 UTC, DavidMinarsch approved these changes

2022-07-05 19:14 UTC, merged