Moved scaffolding contents to its approppriate place
valory-xyz/open-autonomy pull request #1380
Opened 2022-09-22 18:36 UTC by jmoreira-valory

## Proposed changes

Moved scaffolding contents to its approppriate place. Rewritten some parts of the text.

## Fixes

If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [ ] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [ ] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have locally run services that could be impacted and they do not present failures derived from my changes

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-09-22 19:57 UTC, DavidMinarsch commented on docs/guides/create_service_from_scratch.md
> +To simplify the development, the framework provides a scaffold tool that allow developers speed up their flow by auto-generating functional, skeleton classes with all the boilerplate code in place. T
```suggestion
To simplify the development, the framework provides a scaffold tool that allow developers speed up their flow by auto-generating functional, skeleton classes with all the boilerplate code in place. Therefore, you can focus on implementing the actual business logic of the skill, that is part of the service.
```

2022-09-22 19:57 UTC, DavidMinarsch commented on docs/guides/create_service_from_scratch.md
> +To simplify the development, the framework provides a scaffold tool that allow developers speed up their flow by auto-generating functional, skeleton classes with all the boilerplate code in place. T
or something along those lines

2022-09-22 19:58 UTC, DavidMinarsch commented on docs/guides/create_service_from_scratch.md
> +    ```
I think the guide of setting up local registry already exists elsewhere?

2022-09-22 19:59 UTC, DavidMinarsch requested changes
I think there's an opportunity to simplify a bit more

2022-09-23 08:48 UTC, jmoreira-valory commented on docs/guides/create_service_from_scratch.md
> +To simplify the development, the framework provides a scaffold tool that allow developers speed up their flow by auto-generating functional, skeleton classes with all the boilerplate code in place. T
fixed

2022-09-23 09:39 UTC, jmoreira-valory commented
The 'working with packages' guide will be polished in an upcoming PR.

2022-09-23 09:39 UTC, jmoreira-valory commented
The 'working with packages' guide will be polished in an upcoming PR.

2022-09-23 09:56 UTC, DavidMinarsch approved these changes

2022-09-23 09:56 UTC, DavidMinarsch requested changes
CI failing atm - o/w lgtm

2022-09-23 15:12 UTC, DavidMinarsch approved these changes

2022-09-23 15:12 UTC, merged