Extend upgrading guide
valory-xyz/open-autonomy pull request #1567
Opened 2022-11-18 07:38 UTC by angrybayblade

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.

## Fixes

If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [ ] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [ ] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have locally run services that could be impacted and they do not present failures derived from my changes

2022-11-18 07:50 UTC, Adamantios commented on docs/upgrading.md
> +- `AppSpecs` not use dataclasses in order to encapsulate data, which means `response_key`, `response_info`, `error_data`, `retries_attempted` and `backoff_factor` are no longer defined as part of the
```suggestion
- `ApiSpecs` now use dataclasses in order to encapsulate data, which means that `response_key`, and `response_type` can be accessed via the `response_info` instance attribute. Moreover, this attribute now includes the new `response_index` and `error_key`, `error_index`, `error_type`, `error_data`. The `retries_info` instance attribute gives access to the `retries_attempted` and `retries` which are now public and also includes the new `backoff_factor`.
```

2022-11-18 07:53 UTC, Adamantios commented on docs/upgrading.md
> +  - Users will have to manually switch to the newer version
```suggestion
  - Users will have to manually switch to the newer version, i.e., remove the path prefix in all their fsm specs. For example an FSM spec with a `label: packages.author.skills.my_abci.rounds.MyAbciApp` now becomes `label: MyAbciApp`

2022-11-18 08:29 UTC, Adamantios approved these changes

2022-11-18 14:06 UTC, Adamantios commented on docs/upgrading.md
```suggestion

### Test tools

- The `packages.valory.skills.abstract_round_abci.test_tools.apis` module which contained the `DummyMessage` has been removed. `MagicMock` can be used instead. For example, `DummyMessage(my_test_body)` can be converted to `MagicMock(body=my_test_body)`.
```

2022-11-18 14:06 UTC, Adamantios requested changes
Found one more.

2022-11-21 09:55 UTC, DavidMinarsch commented on docs/upgrading.md
>  ## `v0.3.4` to `v0.3.5`
```suggestion
- The `packages.valory.skills.abstract_round_abci.test_tools.apis` module which contained the `DummyMessage` has been removed. `MagicMock` can be used instead. For example, `DummyMessage(my_test_body)` can be converted to `MagicMock(body=my_test_body)`.

## `v0.3.4` to `v0.3.5`
```

2022-11-21 16:27 UTC, merged