feat: add `multicall2` contract
valory-xyz/open-autonomy pull request #1778
Opened 2023-01-27 10:51 UTC by 0xArdi

## Proposed changes

This PR backports the makerDAO multicall2 contract from https://github.com/valory-xyz/agent-academy-1.

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [x] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [ ] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [x] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have locally run services that could be impacted and they do not present failures derived from my changes

2023-01-27 13:57 UTC, Adamantios commented
There is a merge error, you can cherry pick 6278dd37faa4f57839f4deb5d49f9c44ce6ffd7d to resolve this as I also had the same :sweat_smile: .

2023-01-27 13:58 UTC, Adamantios requested changes
Looks good, just a merge error.

2023-01-27 14:27 UTC, 0xArdi commented
The e2e failure is not related. The failure is on `TestRegistrationStartUpFourAgentsCatchUp` because the trigger for resetting agent0 took a bit longer than usual. Additionally, upon restarting agent0 couldnt connect to the local libp2p node.

2023-01-27 14:57 UTC, Adamantios approved these changes
Not a merge error after all: https://github.com/valory-xyz/open-autonomy/pull/1754#issuecomment-1406615277

2023-01-27 15:07 UTC, DavidMinarsch commented on packages/valory/contracts/multicall2/contract.py
> +        raise NotImplementedError
Please add pragma nocovers for the unimplemented methods

2023-01-27 15:19 UTC, Adamantios approved these changes

2023-01-28 10:43 UTC, DavidMinarsch approved these changes

2023-01-28 10:43 UTC, merged