Release v0.9.0
valory-xyz/open-autonomy pull request #1831
Opened 2023-02-16 07:27 UTC by angrybayblade

## Release summary

Version number: 0.9.0

## Release details

Autonomy:
- Updates the on-chain interaction functionalities to wait for the relevant event to make sure the interaction was successful
- Makes the usage of local tendermint chain optional in the deployment setup
- Introduces `autonomy analyse dialogues` command for analysing the dialogue definitions in a skill package
- Introduces `autonomy analyse service` command for checking the deployment readiness of a service
- Introduces `autonomy analyse logs` command for analysing the agent runtime logs
- Adds support for defining custom author name for docker images on the `autonomy build-image` command
- Removes the usage of `MAX_PARTICIPANTS` environment variable from deployment setup
- Adds support for updating the consensus threshold at the runtime using the on-chain metadata

Packages:
- Makes the synchronized database `serializable` and `hashable`
- Backports the `makerDAO multicall2` contract from [`agent-academy-1`](https://github.com/valory-xyz/agent-academy-1) repository
- Simplifies the way the initial height is set on resets. Now, the initial height will always be `0`
- Removes the need for declaring the `payload_attribute` on the round class implementation
- Updates the base rounds to simplify the usage when payloads have multiple attributes
- Adds support for synchronizing the database on registration so that agents can rejoin at any point
- Removes `reset_index` from `AbciApp` implementation
- Adds restrictions on which agents can submit in late message round
- Fixes overlapping blocks by setting unique chain Ids among the tendermint resets
- Updates the rejoin mechanism to
  - Restart tendermint whenever there's a connection drop, from the abci or otherwise
  - Makes sure monitoring is performed even when tendermint is reset by the tendermint server
  - Clean up `timeouts` and `last_timestamp` before trying to restore state received from peers
  - Don't wait for the observation interval in cases when reset is performed for recovery
  - Enables `ACN` communication for rejoining agents, by accepting `requests/responses` from `all_participants`
- Removes consensus from the skills' configurations and replaces the `max_participants` with the length of the `all_participants` list
- Updates the `BaseParams` implementation to enforce minimum values for `observation_interval`
- Updates the `AbciAppDB` implementation to make sure `cross_period_keys` and the database conditions are defined as sets

Tests:
- Adds test coverage for registry contracts
- Adds test for building and running the base autonomy image, the agent runtime image and the tendermint server image
- Re-enables the `fuzzer` tests for the `valory/abci` connection on windows platform

Docs:
- Removes the usage of `max_participants` parameter
- Rearranges the on-chain registration section to match with the autonolas protocol documentation
- Adds a link to the `whitepaper`
- Adds documentation on the deployment readiness checks for a service
- Adds a guide on initializing an empty local packages repository 

Chores:
- Increases `CI` timeout for the tests from `70` minutes to `90` minutes
- Bumps `tomte` to `v0.2.2`

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../main/CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `main` branch (left side), from `develop`
- [ ] I've updated the dependencies versions to the latest, wherever is possible.
- [ ] Lint and unit tests pass locally (please run tests also manually, not only with `tox`)
- [ ] I built the documentation and updated it with the latest changes
- [ ] I've added an item in `HISTORY.md` for this release
- [ ] I bumped the version number in the `__init__.py` file.
- [ ] I published the latest version on TestPyPI and checked that the following command work:
       ```pip install project-name==<version-number> --index-url https://test.pypi.org/simple --force --no-cache-dir --no-deps```
- [ ] After merging the PR, I'll publish the build also on PyPI. Then, I'll make sure the following
      command will work:
      ```pip install project-name-template==<version_number> --force --no-cache-dir --no-deps```  
- [ ] After merging the PR, I'll tag the repo with `v${VERSION_NUMVER}` (e.g. `v0.1.2`)

2023-02-16 08:09 UTC, Adamantios commented on docs/upgrading.md
> +Breaking changes
```suggestion
## `v0.8.0` to `v0.9.0`

Breaking changes

- the `max_participants` have been removed. 
- the `consensus_threshold` should now be specified in the `setup` params. If `null`, then it is calculated automatically.
```

2023-02-16 08:43 UTC, Adamantios approved these changes

2023-02-16 10:58 UTC, angrybayblade commented on autonomy/analyse/service.py
> +                                        "consensus_threshold",
Also added this since this is now required

2023-02-16 13:08 UTC, Adamantios approved these changes

2023-02-16 13:54 UTC, DavidMinarsch requested changes

2023-02-16 13:54 UTC, DavidMinarsch commented on docs/upgrading.md
> +- the `max_participants` have been removed.
removed where? This needs to be a full sentence that's clearly stating where the change occured

2023-02-16 13:54 UTC, DavidMinarsch commented on docs/upgrading.md
> +- the `consensus_threshold` should now be specified in the `setup` parameters. If `null`, then it is calculated automatically.
I would cluster this and the above as subpoints under changes to the configuration

2023-02-16 13:54 UTC, DavidMinarsch commented on docs/upgrading.md
> +- the `consensus_threshold` should now be specified in the `setup` parameters. If `null`, then it is calculated automatically.
```suggestion
- the `consensus_threshold` should now be specified in the `setup` parameters. If `null`, the recommended setting, then it is calculated automatically from the participants provided.
```

2023-02-16 13:54 UTC, DavidMinarsch commented on docs/upgrading.md
> +- The synchronized database is now `serializable` and `hashable`. This means that the data inserted into the database are now enforced to be primitive or non-primitive built-in types only, except for
Why except sets and frozensets. What happens with them?

2023-02-16 13:54 UTC, DavidMinarsch commented on docs/upgrading.md
> +- The usage of local tendermint chain is optional in the deployment setup, use `-ltm, --local-tm-setup` when building a deployment using `autonomy deploy build` command to include a local tendermint
I mentioned before. `local tendermint chain` is not great terminology. We call it Tendermint Consensus Gadget elsewhere cc @jmoreira-valory

2023-02-16 13:54 UTC, DavidMinarsch commented on docs/upgrading.md
> +- The `cross_period_keys` and database conditions needs to be defined as sets
where and how was it defined before? These upgrading sentences need to be more helpful

2023-02-16 13:54 UTC, DavidMinarsch commented on HISTORY.md
> +- Removes the need for declaring the `payload_attribute` on the round class implementation
This is missing from update guide

2023-02-16 13:54 UTC, DavidMinarsch commented on HISTORY.md
> +- Updates the base rounds to simplify the usage when payloads have multiple attributes
Missing explainer in upgrade guide. Specifically regarding changes to rounds

2023-02-16 13:54 UTC, DavidMinarsch commented on HISTORY.md
> +- Removes consensus from the skills' configurations and replaces the `max_participants` with the length of the `all_participants` list
"consensus" -> replace with param in quotes

2023-02-16 13:54 UTC, DavidMinarsch commented on HISTORY.md
> +- Re-enables the `fuzzer` tests for the `valory/abci` connection on windows platform
remove quotes from fuzzer

2023-02-16 13:54 UTC, DavidMinarsch commented on HISTORY.md
> +- Rearranges the on-chain registration section to match with the autonolas protocol documentation
Autonolas not autonolas

2023-02-16 16:20 UTC, angrybayblade commented on autonomy/fsm/scaffold/templates/components.py
> +        db_post_conditions: Dict[AppState, Set[str]] = {{
Just found out the scaffold tool was not up to date with the latest breaking change, is there any other breaking change that should be updated on the scaffold tool? @DavidMinarsch @0xArdi @Adamantios

2023-02-17 07:34 UTC, DavidMinarsch approved these changes

2023-02-17 07:34 UTC, merged