[v0.10.5] Implement remaining on-chain service management tools
valory-xyz/open-autonomy pull request #1956
Opened 2023-05-10 09:33 UTC by angrybayblade

## Proposed changes

- This PR adds support for terminating and unbonding services
  - Add `autonomy service terminate` command
  - Add `autonomy service unbond` command
  - Add `autonomy service info` command
- Updated documentation

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [ ] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [ ] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have locally run services that could be impacted and they do not present failures derived from my changes
- [ ] Public-facing documentation has been updated with the changes affected by this PR. Even if the provided contents are not in their final form, all significant information must be included.
- [ ] Any backwards-incompatible/breaking change has been clearly documented in the upgrading document.

2023-05-10 14:03 UTC, angrybayblade commented on docs/advanced_reference/commands/autonomy_service.md
> +: Timeout for verifying emitted events
@jmoreira-valory `autonomy service` does not have `--skip-hash-check` flag and the doc was missing the `--timeout` flag for the same

2023-05-10 14:03 UTC, angrybayblade commented on docs/advanced_reference/commands/autonomy_service.md
> +```
Useful utility command

2023-05-10 14:37 UTC, jmoreira-valory commented on docs/advanced_reference/commands/autonomy_service.md
> +autonomy service info [OPTIONS] SERVICE_ID
what is "Options" here? I don't see any option. Missing how to choose the chain?

2023-05-10 14:41 UTC, jmoreira-valory commented on docs/advanced_reference/commands/autonomy_service.md
> +This command group consists of a number of functionalities to manage the life cycle of services that have been minted in the [Autonolas Protocol](https://docs.autonolas.network/protocol/). To underst
```suggestion
This command group consists of a number of functionalities to manage [the life cycle of services](https://docs.autonolas.network/protocol/life_cycle_of_a_service/) that have been minted in the [Autonolas Protocol](https://docs.autonolas.network/protocol/).
```

2023-05-10 14:44 UTC, jmoreira-valory commented on docs/advanced_reference/commands/autonomy_service.md
> +Register an agent instance in a service minted and activated in the Autonolas Protocol.
```suggestion
Register an agent instance in a service minted in the [Autonolas Protocol](https://docs.autonolas.network/protocol/). The service must be in the *Active Registration* state.
```

2023-05-10 18:28 UTC, Adamantios requested changes
Changes missing from history.

2023-05-11 04:19 UTC, angrybayblade commented on autonomy/cli/helpers/chain.py
> +from texttable import Texttable
Addressed [ddbbb2e](https://github.com/valory-xyz/open-autonomy/pull/1956/commits/ddbbb2ebf56dd739474a7f95bbbcd7ebdedf00bc)

2023-05-11 06:00 UTC, Adamantios commented on autonomy/cli/helpers/chain.py
> +from texttable import Texttable
Should it be in the `cli_deps` in `setup.py`?

2023-05-16 12:11 UTC, Adamantios submitted a review, later dismissed

2023-05-17 06:37 UTC, Adamantios approved these changes

2023-05-18 07:11 UTC, Adamantios approved these changes

2023-05-18 07:14 UTC, merged