Support for logging to console on tendermint com server
valory-xyz/open-autonomy pull request #2110
Opened 2023-11-21 04:23 UTC by angrybayblade

## Proposed changes

Adds support for logging to console on the tendermint com server

## Fixes

If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [ ] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [ ] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have locally run services that could be impacted and they do not present failures derived from my changes
- [ ] Public-facing documentation has been updated with the changes affected by this PR. Even if the provided contents are not in their final form, all significant information must be included.
- [ ] Any backwards-incompatible/breaking change has been clearly documented in the upgrading document.

2023-11-21 06:58 UTC, angrybayblade reviewed
Tested this locally with trader

2023-11-21 08:07 UTC, DavidMinarsch reviewed
Not sure what the reason was for removing the option to select the type of monitoring. Isn't it simpler to just modify the defaults?

2023-11-21 08:07 UTC, DavidMinarsch commented on deployments/Dockerfiles/tendermint/tendermint.py
> -    def get_node_command_kwargs(monitoring: bool = False) -> Dict:
Hm this approach was more generic. Why are we forcing the approach now?

2023-11-21 08:07 UTC, DavidMinarsch commented on deployments/Dockerfiles/tendermint/tendermint.py
> +    def _monitor_tendermint_process(
Is this a complete copy from below?

2023-11-21 10:30 UTC, solarw commented
@angrybayblade 
tendermint already works well with printing lofs to stdout
i just set log file env variable to /dev/null to avoid on-disk files usage.

so now i can just set WRITE_TO_LOG=false?  and it will stop writing logs to file?

2023-11-21 13:19 UTC, angrybayblade commented
> @angrybayblade tendermint already works well with printing lofs to stdout i just set log file env variable to /dev/null to avoid on-disk files usage.
> 
> so now i can just set WRITE_TO_LOG=false? and it will stop writing logs to file?

Yes

2023-11-21 13:22 UTC, angrybayblade commented on deployments/Dockerfiles/tendermint/tendermint.py
> +    def _monitor_tendermint_process(
Yes

2023-11-21 15:06 UTC, solarw approved these changes
LGTM

2023-11-22 08:37 UTC, DavidMinarsch commented on deployments/Dockerfiles/tendermint/tendermint.py
> -    def get_node_command_kwargs(monitoring: bool = False) -> Dict:
No monitoring was a flag that got passed down. So it was possible to configure.

2023-11-22 08:38 UTC, DavidMinarsch requested changes
What exactly is this PR trying to achieve?

It does change some default behaviour and adds support to configure via env variable and moves some code around. Can we be specific on what we actually want from this PR?

2023-11-22 11:50 UTC, DavidMinarsch approved these changes

2023-11-22 12:21 UTC, solarw approved these changes
lgtm

2023-11-22 12:22 UTC, 0xArdi approved these changes

2023-11-22 16:13 UTC, 0xArdi approved these changes

2023-11-23 03:10 UTC, merged